### ISSUE TITLE
Question about 'Hemispherical Guiding with Spherical Distributions'

### ISSUE THREAD

**Issue by Mephisto405** [cgtuebingen/robust-vmm-guiding#5]
Hello, I enjoy reading your awesome paper on path guiding.
However, there is one detail that I don't understand well. The following sentence appears in the `Hemispherical Guiding with Spherical Distributions subsection`: '_The probability of such samples can be significantly reduced by computing the product with the surface-normal oriented cosine-lobe just before sampling._' I don't understand exactly what it means to compute the cosine before performing sampling. Don't we have to sample the direction vector to calculate the cosine? I'm curious how the normal vector and cosine were used to truncate only the upper hemisphere part from the von-Mises Fisher mixture distribution and sample it unbiasedly.

**Comment by LukasRuppert** [comment]
Hi,
of course, all vMF distributions span the entire sphere - so when sampling them without bias, there are necessarily always a few samples below the hemisphere.
However, when we sample a vMF mixture, we already know our intersection point and its surface normal.
So, instead of sampling the mixture as is, we compute the product of each component with a vMF approximation of the cosine lobe centered around that surface normal.
(Each component will also be weighted by the integral of that product.)
The resulting mixture will be focused much more towards directions on the upper hemisphere and far less towards the lower hemisphere.
Essentially, its the cheapest way of product sampling you can do:
In this case, we only consider the cosine term in the rendering equation.

The relevant code is here:
https://github.com/cgtuebingen/robust-vmm-guiding/blob/b1422737d661ae0f96a104e2d040adfe7d42e753/include/mitsuba/guiding/GuidingDistributionFactoryVMM.h#L167-L171
Here, the `product` function modifies the mixture in place:
https://github.com/cgtuebingen/robust-vmm-guiding/blob/b1422737d661ae0f96a104e2d040adfe7d42e753/include/pmm/VMFKernel.h#L313
And just above you can find the code for the full BSDF (including cosine) product sampling which can deal with multiple lobes.

I hope that is clear enough, I feel like this needs some drawing to come across :)

Best regards,
Lukas

**Comment by Mephisto405** [comment]
OMG, "a vMF approximation of the cosine!" -> That makes sense because the product of two vMF-lobes is as straightforward as your paper described in Appendix A.1, isn't it?
When I first read the paper, I was confused about multiplying the vMF with the cosine. But now I understand that you're multiplying it after approximating the cosine as another vMF. Thank you for explaining it so quickly and clearly.

**Comment by Mephisto405** [comment]
Additionally, I'm wondering why only the first lobe (gBSDF.m_guidingData.m_distributions[0]) is used when sampling the cosine product in `GuidingDistributionFactoryVMM.h`.

**Comment by LukasRuppert** [comment]
The `m_distributions[0]` is actually an entire mixture of up to 32 components.
For the BSDF product, I may have to compute the product with 2 components
which then results in two mixutres `m_distributions[0]` and `m_distributions[1]` which essentially combine into a mixture of up to 64 components.

**Comment by Mephisto405** [comment]
Thank you very much!!
