### ISSUE TITLE
visualizing the guiding field

### ISSUE THREAD

**Issue by arpit12198** [cgtuebingen/robust-vmm-guiding#6]
I am wondering if there is a tool to visualize the guiding field similar to [PPG](https://github.com/Tom94/practical-path-guiding/tree/master/visualizer)

**Comment by LukasRuppert** [comment]
There is no standalone application, but a rich Python API for loading, inspecting and plotting the guiding distributions.

https://github.com/cgtuebingen/robust-vmm-guiding/blob/master/src/libpython/pathguidingutilities.h
https://github.com/cgtuebingen/robust-vmm-guiding/blob/master/src/libpython/guiding.cpp

To compile it, you need to have the boost and Python development libraries installed.
There is also a hard-coded list of Python versions in the Sconscript.configure file:
https://github.com/cgtuebingen/robust-vmm-guiding/blob/b1422737d661ae0f96a104e2d040adfe7d42e753/build/SConscript.configure#L34
Maybe also in some other places

The API allows you to load a scene, the guiding distributions (and optionally sample data) and to then select individual pixels to look at the distributions parameters in detail or plot them.
You can also render a matching view with a spherical camera for reference.
You also have access to the full KD-tree and can export it as an OBJ.
However, its all been some time ago since I've last used it...

Here is some stuff I managed to quickly copy together.
I didn't test it and I've originally still used this with Python 2.7, so it probably needs some work to get running.

```python
import sys, os

mtsdir = '/your/path/to/mitsuba/dist'
sys.path.append(mtsdir + '/python/2.7') # you probably need to adjust this
os.environ['PATH'] = mtsdir + os.pathsep + os.environ['PATH'];

import mitsuba
import mitsuba.core as mtsCore
import mitsuba.render as mtsRender
# Pathguiding Module
import mitsuba.guiding as mtsGuiding

import numpy as np
import matplotlib.pyplot as plt

import multiprocessing

scheduler = mtsCore.Scheduler.getInstance()

# Start up the scheduling system with one worker per local core
for i in range(0, multiprocessing.cpu_count()):
    scheduler.registerWorker(mtsCore.LocalWorker(i, 'wrk%i' % i))
scheduler.start()

fileResolver = mtsCore.Thread.getThread().getFileResolver();
fileResolver.appendPath("../../scenes/torus/");

paramMap = mtsCore.StringMap();
scene = mtsRender.SceneHandler.loadScene(fileResolver.resolve("torus_pathguiding.xml"), paramMap);

scene.configure();
scene.initialize();

# choose whatever pixel you like
pixel = mtsCore.Point2(640,435);
its = mtsGuiding.PathGuidingVerification.getFirstSmoothSurfaceInteraction(scene, pixel);

print(its.p)
print(its.shFrame.n)

# if you like, you can render the scene using a spherical camera with a different integrator here
#sphericalView = mtsGuiding.PathGuidingVerification.renderSphericalView(scene, its.p, "path", 32);
#sphericalView.plot();
#sphericalView.write('torus_640_435.exr');


guidingFieldStream = mtsCore.FileStream('some_guiding_field.serialized', mtsCore.FileStream.EReadOnly);
guidingField = mtsGuiding.GuidingField(guidingFieldStream);

# choose the size of the rendered image of the distribution here
mtsGuiding.PathGuidingUtilities.renderSize = mtsCore.Vector2i(512, 256);

region = guidingField.getRegion(its.p)
# optionally load the matching samples (make sure to export them beforehand - its not enabled by default)
#samples = mtsGuiding.PathGuidingUtilities.loadSampleRange('samples.serialized', region.dStart, region.nSamples);

vmm = region.distribution;
vmmPDF = mtsGuiding.PathGuidingUtilities.renderVMMPDF(vmm);

def getGridAnd2DArrayFromBitmap(bitmap):
    gridRes = bitmap.getSize();
    gridX = np.linspace(math.pi, -math.pi, gridRes.x);
    gridY = np.linspace(0, math.pi, gridRes.y);

    greyscaleBitmap = bitmap.convert(mtsCore.Bitmap.ELuminance, mtsCore.Bitmap.EFloat);
    data = np.array(greyscaleBitmap.buffer());

    return [gridX, gridY, data];

def plotBitmapInFalsecolor(bitmap, alpha=1.0):
    if len(plt.get_fignums()) == 0:
        plt.figure(dpi=100, figsize=[20.0, 6.0]);
    plt.xlabel(r'$\varphi$');
    plt.ylabel(r'$\theta$');
    #this is the way Mitsuba expects envmaps to be laid out
    plt.xlim(math.pi, -math.pi);
    plt.ylim(math.pi, 0.0);

    [gridX, gridY, data] = getGridAnd2DArrayFromBitmap(bitmap);

    plt.imshow(data, extent=[math.pi, -math.pi, math.pi, 0], alpha=alpha, cmap="viridis", norm=FalsecolorNormalize(), resample=False, interpolation='none');

plotBitmapInFalsecolor(vmmPDF);
plt.show();
# alternatively you can also write this bitmap to an exr file
vmmPDF.write('vmm_pdf.exr');
```

**Comment by arpit12198** [comment]
Thanks for digging up the code and also providing the plotting script. I was able to compile and run the script. However, I hit the following bug. 
```
Traceback (most recent call last):
  File "/home/arpit/projects/robust-vmm-guiding/tutorials/vis.py", line 39, in <module>
    its = mtsGuiding.PathGuidingVerification.getFirstSmoothSurfaceInteraction(scene, pixel);
AttributeError: module 'mitsuba.guiding' has no attribute 'PathGuidingVerification'
```
I couldn't find any such class. My guess is that shoots a path to find a diffuse surface. Is there any other quick hack to make the script run?

**Comment by LukasRuppert** [comment]
There have been a few changes in how things are named and structured during development.
I've now tried it myself and added the fixed script to the repository:
https://github.com/cgtuebingen/robust-vmm-guiding/blob/master/plot_distribution.py
I've also added the necessary changes to compile the python plugin on Ubuntu 22.04.
I've also changed the C++ version from 11 to 17. That is probably not necessary, so revert that if you don't want to recompile.

Let me know if you need anything else.

**Comment by arpit12198** [comment]
Thanks for the update. The script works for me now.
